Pern3/Pern/main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^studentsFollowing$', views.studentsFollowing, name='studentsF'),
    url(r'^history$', views.history, name='history'),
    url(r'^rotations$', views.rotations, name='rotations'),
    url(r'^makeQueries$', views.ajaxQueries, name='ajax'),
    url(r'^projects$', views.projectsFollowing, name='projects'),
]

Pern3/Pern/pern/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls', namespace = "app_main")),
]

Pern3/Pern/main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import os, sys
from django.db import models

##################################USUARIOS##################################
class User(models.Model):
    name = models.CharField(max_length=128)
    surname = models.CharField(max_length=128)
    email = models.EmailField(max_length=254)
    dni = models.IntegerField()
    idUser = models.AutoField(primary_key=True)

    class Meta:
        abstract = True

##################################PROFESOR##################################
class Teacher(User):
    boss = models.BooleanField(blank=True)
    password = models.CharField(max_length=18)


    class Meta:
        verbose_name = 'Profesor'
        verbose_name_plural = 'Profesores'
    def __str__(self):
        tagName = str(self.name)
        return tagName

##################################CURSOS##################################
class Course(models.Model):
    idCourse = models.AutoField(primary_key=True)
    cycle = models.IntegerField()
    COURSE_OPTIONS = (
    (u'1', u'1º año'),
    (u'2', u'2º año'),
    (u'3', u'3º año'),
    )
    DIVISION_OPTIONS = (
    (u'A', u'A'),
    (u'B', u'B'),
    (u'C', u'C'),
    )
    courseType = models.CharField(max_length=128, choices=COURSE_OPTIONS)
    courseDivision = models.CharField(max_length=128, choices=DIVISION_OPTIONS)


    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'

    def __str__(self):
        tagName = str(self.courseType) + str(self.courseDivision) + " - " + str(self.cycle)
        return tagName

##################################MODULOS##################################
class Module(models.Model):
    idModule = models.AutoField(primary_key=True)
    nameModule = models.CharField(max_length=128)
    idCourse = models.ForeignKey(Course, blank=True)


    class Meta:
        verbose_name = 'Modulo'
        verbose_name_plural = 'Modulos'
    def __str__(self):
        tagName = str(self.nameModule)
        return tagName

##################################ROTACIONES##################################
class Rotation(models.Model):
    nameRotation = models.CharField(max_length=32)
    idRotation = models.AutoField(primary_key=True)
    idModule = models.ForeignKey(Module)
    idCourse = models.ForeignKey(Course)

    class Meta:
        verbose_name = 'Rotacion'
        verbose_name_plural = 'Rotaciones'
    def __str__(self):
        tagName = str(self.nameRotation) + "(" + str(self.idModule) + ")"
        return tagName

##################################ALUMNO##################################
class Student(User):
    idCourse = models.ForeignKey(Course)
    idRotation = models.ForeignKey(Rotation, blank=True, null=True)
    numberOfRegistration = models.IntegerField()

    class Meta:
        verbose_name = 'Alumno'
        verbose_name_plural = 'Alumnos'
    def __str__(self):
        tagName = str(self.name)+" "+str(self.surname)+ " [" + str(self.idRotation) + "]"
        return tagName

##################################DOCUMENTOS##################################
class Document(models.Model):
    idDocument = models.AutoField(primary_key=True)
    nameDocument= models.CharField(max_length=128)
    visible = models.BooleanField(blank=True)
    idModule = models.ManyToManyField(Module, blank=True)


    class Meta:
        verbose_name = 'Documento'
        verbose_name_plural = 'Documentos'
    def __str__(self):
        tagName = str(self.nameDocument) + "(" + str(self.idModule) + ")"
        return tagName

##################################PROYECTOS##################################
class Project(models.Model):
    nameProject = models.CharField(max_length=128)
    idProject = models.AutoField(primary_key=True)
    idTeacher = models.ManyToManyField(Teacher)
    idModule = models.ForeignKey(Module)


    class Meta:
        verbose_name = 'Proyecto'
        verbose_name_plural = 'Proyectos'
    def __str__(self):
        tagName = str(self.nameProject) + "[" + str(self.idModule) + "]" + "(" + str(self.idTeacher) + ")"
        return tagName

##################################CUMPLIMIENTOS##################################
class Fulfillment(models.Model):
    nameFF = models.CharField(max_length=128)
    idFF = models.AutoField(primary_key=True)
    idProject = models.ManyToManyField(Project, blank=True)


    class Meta:
        verbose_name = 'Cumplimiento'
        verbose_name_plural = 'Cumplimientos'
    def __str__(self):
        tagName = str(self.nameFF) + "(" + str(self.idProject) + ")"
        return tagName

##################################SEGUIMIENTO DE ALUMNO##################################
class studentsFollowingModel(models.Model):
    idSF = models.AutoField(primary_key=True)
    presenceSF = models.BooleanField(blank=True)
    dateSF = models.DateField()
    idModule = models.ForeignKey(Module)
    idStudent = models.ForeignKey(Student)
    idTeacher = models.ManyToManyField(Teacher)
    commentPF = models.TextField(blank=True)

    class Meta:
        verbose_name = 'Seguimiento de Alumno'
        verbose_name_plural = 'Seguimientos de Alumno'
    def __str__(self):
        tagName = '['+str(self.dateSF)+"]"+str(self.idStudent) + "(" + str(self.idModule) + ")"
        return tagName

#############################CUMPLIMIENTOS EN CLASE#############################
class classFulfillment(models.Model):
    idFF = models.ForeignKey(Fulfillment)
    idSF = models.ForeignKey(studentsFollowingModel)
    check = models.BooleanField(blank=True)

    class Meta:
        verbose_name = 'Cumplimiento en clase'
        verbose_name_plural = 'Cumplimientos en clase'
        def __str__(self):
            tagName = str(self.nameFF) + "(" + str(self.idSF) + ")"
            return tagName
##################################ACTIVIDADES##################################
class Activity(models.Model):
    nameActivity = models.CharField(max_length=128)
    idActivity = models.AutoField(primary_key=True)
    idProject = models.ForeignKey(Project)

    def natural_key(self):
        return (self.idActivity, self.nameActivity, self.idProject.nameProject)

    class Meta:
        verbose_name = 'Actividad'
        verbose_name_plural = 'Actividades'
    def __str__(self):
        tagName = str(self.nameActivity) + "[" + str(self.idProject) +"]"
        return tagName

##################################TRABAJA##################################
class Working(models.Model):
    idStudent = models.ForeignKey(Student)
    idActivity = models.ForeignKey(Activity)
    numberOfClasses = models.IntegerField()
    calification = models.IntegerField(blank=True, null=True)
    hasFinish = models.BooleanField(blank=True)


    class Meta:
        verbose_name = 'Trabajo'
        verbose_name_plural = 'Trabajos'
    def __str__(self):
        tagName = str(self.idActivity) + " " + str(self.idStudent)
        return tagName

##################################TRABAJA##################################
class OnClass(models.Model):
    idActivity = models.ForeignKey(Activity, null=True, blank=True)
    idSF = models.ForeignKey(studentsFollowingModel)

    class Meta:
        verbose_name = 'Trabajo en Clase'
        verbose_name_plural = 'Trabajos en Clase'

Pern3/Pern/main/views.py
# -*- coding: utf-8 -*-
#Importaciones
from django.template import RequestContext
from django.shortcuts import render_to_response, render, redirect
from django.core import serializers
from django.http import HttpResponse
from models import *
import json
from django.core.exceptions import ObjectDoesNotExist
from itertools import chain

#Seguimiento de alumnos
def studentsFollowing(request):
    context = RequestContext(request)
    courses = Course.objects.all()
    pupils = Student.objects.all()
    subjects = Module.objects.all()
    return render_to_response('studentsFollowing.html', {'courses':courses, 'subjects':subjects, 'pupils':pupils},context)

#Historial de los alumnos
def history(request):
    context = RequestContext(request)
    return render_to_response('history.html', context)

#Rotaciones
def rotations(request):
    context = RequestContext(request)
    return render_to_response('rotations.html', context)

#Seguimiento de proyectos
def projectsFollowing(request):
    context = RequestContext(request)
    return render_to_response('projectsFollowing.html', context)

#Peticiones AJAX
def ajaxQueries(request):
    queryId = request.GET.get('queryId')
    info = ''
    data = ''

    if(queryId == 'modulesByCourse'):
        idC = int(request.GET.get('idCourse'))
        data = Module.objects.filter(idCourse__idCourse=idC)

    elif(queryId == 'studentsByRotation'):
        idR = request.GET.get('idRotation')
        data = Student.objects.filter(idRotation__idRotation=idR).order_by('surname')

    elif(queryId == 'rotationsByModule'):
        module = request.GET.get('idModule')
        data = Rotation.objects.filter(idModule__idModule=module)

    elif(queryId == 'projectsByModule'):
        idM = int(request.GET.get('module'))
        data = Project.objects.filter(idModule__idModule=idM)

    elif(queryId == 'studentById'):
        idU = int(request.GET.get('idStudent'))
        data = Student.objects.filter(idUser=idU)

    elif(queryId == 'activitiesByProject'):
        idP = int(request.GET.get('idProject'))
        data = Activity.objects.filter(idProject__idProject=idP)

    elif(queryId == 'working'):
        idS  = request.GET.get('idStudent')
        idA = request.GET.get('idActivity')
        student = Student.objects.get(idUser=idS)
        activity = Activity.objects.get(idActivity=idA)
        try:
            Working.objects.get(idStudent__idUser=idS, idActivity__idActivity=idA)
        except ObjectDoesNotExist:
            newWorking = Working()
            newWorking.idStudent = student
            newWorking.idActivity = activity
            newWorking.numberOfClasses = 0
            newWorking.hasFinish = False
            newWorking.save()
        data = Working.objects.filter(idStudent__idUser=idS, idActivity__idActivity=idA)
        numberOC = len(OnClass.objects.filter(idActivity__idActivity=idA,idSF__idStudent__idUser=idS))
        data.update(numberOfClasses=numberOC)


    elif(queryId == "activitiesByProject"):
        idP = int(request.GET.get('idProject'))
        data = Activity.objects.filter(idProject__idProject=idP)

    elif(queryId == "getCurrentActivity"):
        data = []
        idM = request.GET.get('idModule')
        date = request.GET.get('date')
        studentsFollowing = studentsFollowingModel.objects.filter(dateSF=str(date),idModule__idModule=idM)
        for x in studentsFollowing:
            work = OnClass.objects.get(idSF=x).idActivity
            if(work != None):
                dictionary = {'studentId': x.idStudent.idUser,'activity': work.idActivity}
            else:
                dictionary = {'studentId': x.idStudent.idUser,'activity': "zero"}
            data.append(dictionary)
        data = json.dumps(data)
        print("\033[1m RESPUESTA A " + queryId + "\033[0m")
        print(data)
        return HttpResponse(data)

    elif(queryId == "saveActivity"):
        idS = request.GET.get('idStudent')
        idM = request.GET.get('idModule')
        idA = request.GET.get('activity')
        date = request.GET.get('date')
        data = OnClass.objects.filter(idSF__idStudent__idUser=idS, idSF__idModule__idModule=idM, idSF__dateSF=date)
        if(idA != "zero"):
            activity = Activity.objects.get(idActivity=idA)
            data.update(idActivity=activity)
        else:
            data.update(idActivity=None)

    elif(queryId == "createAllSF"):
        date = request.GET.get('date')
        module = request.GET.get('idModule')
        students = Student.objects.filter(idRotation__idModule__idModule=module).order_by('surname')
        for student in students:
            try:
                studentsFollowingModel.objects.get(dateSF=str(date),idModule__idModule=module, idStudent__idUser= student.pk)
            except ObjectDoesNotExist:
                newSF = studentsFollowingModel()
                newSF.presenceSF = True
                newSF.dateSF = str(date)
                newSF.idModule = Module.objects.get(idModule=module)
                newSF.idStudent = student
                newSF.commentPF = ''
                newSF.save()
                newSF.idTeacher.add(Teacher.objects.get(idUser=1)) #TODO meter un profesor de verdad
                newSF.save()
        data = studentsFollowingModel.objects.filter(dateSF=str(date),idModule=module)

    elif(queryId == "createAllCW"):
        date = request.GET.get('date')
        module = request.GET.get('idModule')
        sFs = studentsFollowingModel.objects.filter(dateSF=str(date),idModule__idModule=module)
        for sF in sFs:
            try:
                OnClass.objects.get(idSF=sF)
            except ObjectDoesNotExist:
                newOc = OnClass()
                newOc.idSF = sF
                newOc.save()
        data = OnClass.objects.filter(idSF__idModule=module,idSF__dateSF=date)

    elif(queryId == "createAllFF"):
        idP = request.GET.get('idProject')
        idS = request.GET.get('idStudent')
        idM = request.GET.get('idModule')
        date = request.GET.get('date')
        fulfillments = Fulfillment.objects.filter(idProject__idProject=idP).order_by('nameFF')
        studentFollowing = studentsFollowingModel.objects.get(dateSF=str(date),idModule__idModule=idM, idStudent__idUser= idS)
        for fulfillment in fulfillments:
            try:
                classFulfillment.objects.get(idFF=fulfillment, idSF=studentFollowing)
            except ObjectDoesNotExist:
                data = classFulfillment()
                data.idFF = fulfillment
                data.idSF = studentFollowing
                data.check = True
                data.save()
        data = classFulfillment.objects.filter(idFF__idProject=idP,idSF=studentFollowing)


    elif(queryId == "getStudentFollowing"):
        idS = request.GET.get('idStudent')
        idM = request.GET.get('idModule')
        date = request.GET.get('date')
        data = studentsFollowingModel.objects.filter(dateSF=str(date),idModule__idModule=idM, idStudent__idUser= idS)

    elif(queryId == 'saveFulfillment'):
        idS = request.GET.get('idStudent')
        idM = request.GET.get('idModule')
        date = request.GET.get('date')
        idFF = request.GET.get('fulfillmentId')
        studentF  = studentsFollowingModel.objects.filter(dateSF=str(date),idModule__idModule=idM, idStudent__idUser= idS)
        data = classFulfillment.objects.filter(idFF__idFF=idFF,idSF=studentF)
        data.update(check = not data[0].check)

    elif(queryId == 'calcAccuracy'):
        idS = request.GET.get('idStudent')
        idM = request.GET.get('idModule')
        idFF = request.GET.get('idFF')
        classQuantity  = len(classFulfillment.objects.filter(idFF__idFF=idFF,idSF__idStudent__idUser=idS))
        classTrue  = len(classFulfillment.objects.filter(idFF__idFF=idFF,idSF__idStudent__idUser=idS,check=True))
        info  = (float(classTrue) / float(classQuantity))*100
        return HttpResponse(info)


    elif(queryId == 'saveObservations'):
        idS = request.GET.get('idStudent')
        idM = request.GET.get('idModule')
        date = request.GET.get('date')
        text = request.GET.get('text')
        data = studentsFollowingModel.objects.filter(dateSF=str(date),idModule__idModule=idM, idStudent__idUser= idS)
        data.update(commentPF = text)

    elif(queryId == 'savePresence'):
        idS = request.GET.get('idStudent')
        idM = request.GET.get('idModule')
        date = request.GET.get('date')
        data = studentsFollowingModel.objects.filter(dateSF=str(date),idModule__idModule=idM, idStudent__idUser= idS)
        data.update(presenceSF= not data[0].presenceSF)

    elif(queryId == 'fulfillmentsByProject'):
        idP = request.GET.get('idProject')
        data = Fulfillment.objects.filter(idProject__idProject=idP).order_by('nameFF')


    if(data != ''):
        info = serializers.serialize('json', data)
    else:
        info = "La siguiente queryId no existe: '" + queryId +"'"
    print("\033[1m RESPUESTA A " + queryId + "\033[0m")
    print(info)
    return HttpResponse(info)

Pern3/Pern/main/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <script> var url = '{% url "app_main:ajax" %}';</script>
    <script src="{% static 'js/jquery-3.1.0.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <link href="{% static 'css/bootstrap-select.css' %}" rel="stylesheet">
    <script type="text/javascript"></script>
    {% block scripts %}
    {% endblock %}
    <head>
        <meta name="description" content="Administracion para escuelas tecnicas">
        <meta name="author" content="TechnoMuffin">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--<link rel="icon" href="../../favicon.ico">--> <!--Icono de la página-->
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <title>Pern</title>
        {% block css %}
        {% endblock %}
    </head>
    <body style="margin-top:70px">
        <nav class="navbar navbar-default navbar-fixed-top" style="color:white;">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" style="color:white; font-weight: bold;">Pern</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li {% block link1 %}{% endblock %}><a class="navbar-a" href="{% url 'app_main:studentsF' %}" style="color:white;">Seguimiento Diario</a></li>
                        <li {% block link2 %}{% endblock %}><a class="navbar-a" href="{% url 'app_main:projects' %}" style="color:white;">Proyectos</a></li>
                        <li {% block link3 %}{% endblock %}><a class="navbar-a" href="{% url 'app_main:history' %}" style="color:white;">Historial</a></li>
                        <li {% block link4 %}{% endblock %}><a class="navbar-a" href="{% url 'app_main:rotations' %}" style="color:white;">Rotaciones</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </body>
</html>

Pern3/Pern/main/templates/history.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block link3 %}
class='active'
{% endblock %}
{% block content %}
<div class="container col-xs-12">
    <div class="col-xs-12 col-md-12">
        <!-- Panel "Alumnos" -->
        <div class="col-xs-12 col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Historial
                </div>
                <div class="panel-body">
                    <div class="form-group col-xs-12 col-md-4">
                        <select id="cbxCourse" class="selectpicker" data-width="100%">
                            <option value=''>Curso</option>
                            {% for i in courses %}
                            <option value={{i.idCourse}}>{{i.courseType}}º año "{{i.courseDivision}}"</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group col-xs-12 col-md-4">
                        <select id="cbxModule" class="selectpicker" data-width="100%">
                            <option value=''>Módulo</option>
                        </select>
                    </div>
                    <div class="form-group col-xs-12 col-md-4">
                        <select id="cbxStudent" class="selectpicker" data-width="100%">
                            <option value=''>Alumno</option>
                        </select>
                    </div>
                    <div class="table table-responsive">
                        <table class="table table-responsive" id="historyTable">
                            <thead>
                                <tr>
                                    <th class='col-xs-1'>Presente</th>
                                    <th class='col-xs-3'>Fecha</th>
                                    <th class='col-xs-6'>Tarea</th>
                                    <th class='col-xs-1'></th>
                                </tr>
                            </thead>
                            <tbody id="tbHistory">
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'js/bootstrap-select.js'%}"></script>
<script src="{% static 'js/history.js'%}"></script>
{% endblock %}

Pern3/Pern/main/templates/projectsFollowing.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block link2 %}
class='active'
{% endblock %}
{% block content %}
<div class="container">
    <div class="col-xs-12 col-md-4">
        <div class="col-xs-12 col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Alumnos
                </div>
                <div class="panel-body">
                    <div class="form-group col-xs-12 col-md-6">
                        <select id="cbxCourse" class="selectpicker" data-width="100%">
                            <option value=''>Curso</option>
                            {% for i in courses %}
                            <option value={{i.idCourse}}>{{i.courseType}}º año "{{i.courseDivision}}"</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group col-xs-12 col-md-6">
                        <select id="cbxModule" class="selectpicker" data-width="100%">
                            <option value=''>Módulo</option>
                        </select>
                    </div>
                    <div class="form-group col-xs-12">
                        <select id="cbxProjectFW" class="selectpicker" data-width="100%">
                            <option value=''>Proyecto</option>
                        </select>
                    </div>
                    <div class="form-group col-xs-12">
                        <div class="input-group col-xs-12">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                                </button>
                            </span>
                            <input type="text" class="form-control" id="datepicker" name="date" placeholder="Fecha" value="2016-10-09">
                        </div>
                    </div>
                    <div>
                        <table class="table table-responsive" id="myTable">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Alumno</th>
                                    <th>Actividad</th>
                                </tr>
                            </thead>
                            <tbody id="tbAlumnos">
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-md-8 ">
        <div class="col-xs-12">
            <div class="panel panel-default">

                <div class="panel-heading">Panel heading</div>
                <!-- Table -->
                <table class="table">
                    <thead>
                        <tr>
                            <th>Etapa</th>
                            <th>Calificacion</th>
                            <th>Estrellas</th>

                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Etapa 1</td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>Etapa 2</td>
                            <td></td>
                            <td></td>

                        </tr>
                        <tr>
                            <td>Etapa 3</td>
                            <td></td>
                            <td></td>

                        </tr>
                        <tr>
                            <td>Etapa 4</td>
                            <td></td>
                            <td></td>

                        </tr>
                        <tr>
                            <td>Etapa 5</td>
                            <td></td>
                            <td></td>

                        </tr><tr>
                        <td>Etapa 6</td>
                        <td></td>
                        <td></td>

                        </tr><tr>
                        <td>Etapa 7</td>
                        <td></td>
                        <td></td>

                        </tr><tr>
                        <td>Etapa 8</td>
                        <td></td>
                        <td></td>

                        </tr><tr>
                        <td>Etapa 9</td>
                        <td></td>
                        <td></td>

                        </tr><tr>
                        <td>Etapa 10</td>
                        <td></td>
                        <td></td>

                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-md-5 hidden-xs" style="width:54%; margin-left:886px;"><button style="width:36%;" type="button" class="btn btn-default">Terminado <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button></div>
    <div class="col-xs-12 col-md-5 visible-xs"><button style="width:93%; margin-left: 15px;" type="button" class="btn btn-default">Terminado <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button></div>

    {% endblock %}
    {% block scripts %}
    <script src="{% static 'js/bootstrap-select.js'%}"></script>
    {% endblock %}