Pern2/Main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^seguimientoAlumno$', views.pupilFollowing, name='seg-al'),
    url(r'^historial$', views.history, name='history'),
    url(r'^rotacionAlumno$', views.rotation, name='rot-al'),
    url(r'^proyectos$', views.projectFollowing, name='projects'),
    url(r'^makeQueriesStudentFollowing$', views.StudentFollowingAjaxQueries, name='sfAjax'),
    url(r'^documents$', views.document, name='doc'),
    url(r'^modulos$', views.modules, name='modules')
]

Pern2/Pern/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Main.urls', namespace = "app_main")),
]

Pern2/Main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Pern2/Main/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm, ClearableFileInput
from django import forms
from database.models import Document

class CustomClearableFileInput(ClearableFileInput):
    template_with_clear = '<br>  <label for="%(clear_checkbox_id)s">%(clear_checkbox_label)s</label> %(clear)s'

class FormEntrada(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('nameDocument', 'idCourse','idModule', 'archivo','commentDoc')
        widgets = {
            'archivo': CustomClearableFileInput
        }

Pern2/Main/views.py
# -*- coding: utf-8 -*-
from django.template import RequestContext
from django.shortcuts import render_to_response, render, redirect
from django.core import serializers
from django.http import HttpResponse
from database.models import *
import json
from django.core.exceptions import ObjectDoesNotExist
from itertools import chain
from forms import FormEntrada
import datetime

def pupilFollowing(request):
    queryId = request.GET.get('queryId')
    info = '...'
    if request.is_ajax():
        if(queryId == "subjects"):
            # Devuelve todos los modulos correspondientes al curso
            idC = request.GET.get('idCourse')
            if(idC != ''):
                curso = Course.objects.get(idCourse=int(idC))
                modulos = Module.objects.filter(exists=True, idCourse=curso)
                info = serializers.serialize('json', modulos)
            else:
                info = "ERROR: No existe el modulo pedido"

        elif(queryId == "projects"):
            # Devuelve todos los proyectos correspondientes al modulo
            idModule = request.GET.get('module')
            if(idModule != ''):
                module = Module.objects.get(exists=True, idModule=int(idModule))
                projects = Project.objects.filter(exists=True,idModule=module)
                info = serializers.serialize('json', projects)
            else:
                info = "ERROR: No existe el proyecto pedido"

        elif(queryId == "dailyFulfillments"):
            # Devuelve todos los cumplimientos necesarios para ese dia, si no
            # existen seran creados y devueltos
            idModule = request.GET.get('idModule')
            idProject = request.GET.get('idProject')
            idStudent = request.GET.get('idStudent')
            date = request.GET.get('date')
            if(idModule != '' or idProject != '' or idStudent != '' or idStudent != '' or date != ''):
                sf = StudentFollowingModel.objects.get(exists=True,idModule__idModule=int(idModule), idStudent__idUser=int(idStudent), dateSF=str(date))
                dailyFF = dailyFulfillment.objects.filter(idSF=sf)
                if not dailyFF:
                    modelFF = Fulfillment.objects.filter(idProject__idProject=int(idProject))
                    for i in modelFF:
                        dailyFF = dailyFulfillment()
                        dailyFF.idSF = sf
                        dailyFF.idFF = i
                        dailyFF.done = True
                        dailyFF.save()
                    dailyFF = dailyFulfillment.objects.filter(idSF=sf)
                info = serializers.serialize(
                    'json', dailyFF, use_natural_foreign_keys=True)
            else:
                info = "ERROR: No existe el cumplimiento"

        elif(queryId == "activities"):
            # Devuelve todos las actividades correspondientes al proyecto
            idProject = request.GET.get('idProject')
            if(idProject != ''):
                project = Project.objects.get(exists=True,idProject=int(idProject))
                activities = Activity.objects.filter(idProject=project)
                info = serializers.serialize('json', activities)
            else:
                info = "ERROR: No existen actividades para este proyecto"

        elif(queryId == "working"):
            # Devuelve la informacion del trabajo correspondiente a la
            # actividad seleccionada
            idActivity = request.GET.get('idActivity')
            idStudent = request.GET.get('idStudent')
            if(idActivity != ''):
                activity = Activity.objects.get(idActivity=int(idActivity))
                student = Student.objects.get(idUser=int(idStudent))
                try:
                    work = Working.objects.get(
                        idActivity=activity, idStudent=student)
                    info = serializers.serialize('json', [work, activity])
                except ObjectDoesNotExist:
                    # Si el trabajo no existe, se creara uno nuevo y se enviara
                    newWork = Working()
                    newWork.idActivity = activity
                    newWork.idStudent = student
                    newWork.numberOfClasses = 0
                    newWork.calification = 0
                    newWork.hasFinish = False
                    newWork.save()
                    info = serializers.serialize('json', [newWork, activity])
            else:
                info = 'ERROR: No hay trabajo para esa actividad'

        elif(queryId == "createSF"):
            date = request.GET.get('date')
            module = request.GET.get('idModule')
            module = Module.objects.get(idModule=int(module))
            students = Student.objects.filter(idRotation__idModule=module).order_by('surname')
            sfs = StudentFollowingModel.objects.filter(
                dateSF=str(date), idModule=module)
            if not sfs:
                for i in students:
                    newSF = StudentFollowing()
                    newSF.presenceSF = True
                    newSF.dateSF = str(date)
                    newSF.idModule = module
                    newSF.idStudent = i
                    newSF.commentPF = ''
                    newSF.save()
                    # TODO meter un profesor de verdad
                    newSF.idTeacher.add(Teacher.objects.get(idUser=1))
                    newSF.save()
            info = '...'
        elif(queryId == "students"):
            # Devuelve todos los alumnos pertenecientes al curso y al modulo
            idC = request.GET.get('idCourse')
            idPFW = request.GET.get('idProjectFW')
            module = request.GET.get('idModule')
            curso = Course.objects.get(idCourse=int(idC))
            module = Module.objects.filter(idModule=int(module))
            students = Student.objects.filter(idCourse=int(idC), idRotation__idModule=module).order_by('surname')
            # Si no me mandan idPFW...
            if(idPFW is not None):
                project = Project.objects.filter(idProject=int(idPFW))
                activity = Activity.objects.filter(
                    idProject=project).order_by('idActivity')
                combined = list(chain(students, activity))
                info = serializers.serialize('json', combined)
            else:
                #...te serializo los estudiantes solos
                info = serializers.serialize('json', students)

        elif(queryId == "studentsByCourse"):
            # Devuelve todos los alumnos pertenecientes al curso y al modulo
            idC = request.GET.get('idCourse')
            curso = Course.objects.get(idCourse=int(idC))
            students = Student.objects.filter(idCourse=int(idC)).order_by('surname')
            info = serializers.serialize('json', students)

        elif(queryId == "rotationsByModule"):
            # Devuelve todas las rotaciones que actualmente estan trabajando en
            # el modulo pedido
            module = request.GET.get('idModule')
            module = Module.objects.get(idModule=module)
            rotations = Rotation.objects.filter(exists=True,idModule=module)
            info = serializers.serialize('json', rotations)

        elif(queryId == "studentsByRotation"):
            # Devuelve todos los alumnos pertenecientes a la rotacion
            rotation = request.GET.get('idRotation')
            print("ID: " + str(rotation))
            if(rotation != '0'):
                rotation = Rotation.objects.get(idRotation=int(rotation))
                students = Student.objects.filter(
                    idRotation=rotation).order_by('surname')
                info = serializers.serialize('json', students)
            else:
                students = Student.objects.filter(idRotation=None).order_by('surname')
                info = serializers.serialize('json', students)

        elif(queryId == "onlyStudent"):
            # Devuelve el alumno pedido
            idUser = request.GET.get('idStudent')
            student = Student.objects.filter(idUser=int(idUser))
            info = serializers.serialize('json', student)
        elif(queryId == "rotations"):
            # Devuelve las rotaciones
            course = request.GET.get('idCourse')
            if(course != ''):
                course = Course.objects.get(idCourse=course)
                rotations = Rotation.objects.filter(exists=True,idCourse=course)
                info = serializers.serialize('json', rotations, use_natural_foreign_keys=True)
            else:
                info = "Curso Invalido"

        elif(queryId == "deleteRotation"):
            # Devuelve las rotaciones
            rotation = request.GET.get('idRotation')
            if(rotation != '0'):
                rotation = Rotation.objects.get(idRotation=int(rotation))
                students = Student.objects.filter(idRotation=rotation)
                students.update(idRotation=None)
                rotation.update(exists=False)
                info = 'Rotacion eliminada'
            else:
                info = "Rotacion Invalida"

        elif(queryId == "updateRotation"):
            # Devuelve las rotaciones
            module = request.GET.get('idModule')
            rotation = request.GET.get('idRotation')
            if(rotation != ''):
                module = Module.objects.get(idModule=int(module))
                Rotation.objects.filter(idRotation=int(rotation)).update(idModule=module)
                info = 'Rotacion cambiada'
            else:
                info = "Error"

        elif(queryId == "studentsByRotation"):
            # Devuelve los alumnos filtrados por rotacion
            rotation = request.GET.get('idRotation')
            if(rotation != '0'):
                rotation = Rotation.objects.get(idRotation=int(rotation))
                students = Student.objects.filter(
                    idRotation=rotation).order_by('surname')

Pern2/Main/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta name="description" content="Administracion para escuelas tecnicas">
        <meta name="author" content="TechnoMuffin">
        <meta charset="utf-8">
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" /> 
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--<link rel="icon" href="../../favicon.ico">-->
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-select.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-datepicker.css' %}" rel="stylesheet">
        <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <title>Pern</title>
        {% block css %}
        {% endblock %}
    </head>
    <body style="margin-top:70px">
        <nav class="navbar navbar-default navbar-fixed-top" style="color:white;">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" style="color:white; font-weight: bold;"><img src="{% static 'img/logo.svg' %}" width="80%"></a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li {% block link1 %}{% endblock %}><a class="navbar-a" href="{% url 'app_main:seg-al' %}" style="color:white;">Seguimiento Diario</a></li>
                        <li {% block link2 %}{% endblock %}><a class="navbar-a" href="{% url 'app_main:projects' %}" style="color:white;">Proyectos</a></li>
                        <li {% block link3 %}{% endblock %}><a class="navbar-a" href="#pupils" style="color:white;">Alumnos</a></li>
                        <li {% block link4 %}{% endblock %}><a class="navbar-a" href="{% url 'app_main:history' %}" style="color:white;">Historial</a></li>
                        <li {% block link5 %}{% endblock %}><a class="navbar-a" href="{% url 'app_main:rot-al' %}" style="color:white;">Grupo de Alumnos</a></li>
                        <li {% block link6 %}{% endblock %}><a class="navbar-a" href="{% url 'app_main:modules' %}" style="color:white;">Rotaciones</a></li>
                        <li {% block link7 %}{% endblock %}><a class="navbar-a" href="{% url 'app_main:doc' %}" style="color:white;">Documentos</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </body>
    <script src="{% static 'js/jquery-3.1.0.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</html>

Pern2/Main/templates/documents.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block link7 %}
class='active'
{% endblock %}
{% block content %}
<div class="container">
    <div class="col-xs-12 ">
        <!-- Panel "Alumnos" -->
        <div class="col-xs-12 ">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Alumnos
                </div>
                <div class="panel-body ">
                    <div class="form-group col-xs-12 col-md-6">
                        <select id="cbxCourseB" class="selectpicker" data-width="100%">
                            <option value=''>Curso</option>
                            {% for i in courses %}
                            <option value={{i.idCourse}}>{{i.courseType}}º año "{{i.courseDivision}}"</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group col-xs-12 col-md-6">
                        <select id="cbxModuleB" class="selectpicker" data-width="100%">
                            <option value=''>Módulo</option>
                        </select>
                    </div>



                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12">
        <!-- Panel "Alumnos" -->
        <div class="col-xs-12 ">
            <div class="panel panel-default">
                <div class="panel-heading">
                  Documentos
                </div>
                <div class="panel-body table-responsive">
                    <table class="table table-responsive" id="docTable">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Nombre</th>
                                <th>Profesor</th>
                                <th>Curso</th>
                                <th>Modulo</th>
                                <th>Descripcion</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody id="tbDocument">
                          <tr>
                              <td><a href="#"><i class="glyphicon glyphicon-file"></i></a></td>
                              <td>Plano Martillo</td>
                              <td>Eintein</td>
                              <td>3 C</td>
                              <td>Ajuste</td>
                              <td>Plano necesario</td>
                              <td><a href="#"><i class="glyphicon glyphicon-edit"></i></a>
                                <a href="#"><i class="glyphicon glyphicon-trash" style="left: 10px;"></i></a>
                                <a href="#"><i class="glyphicon glyphicon-save" style="left: 20px;"></i></a></td>
                          </tr>
                          <tr>
                              <td><a href="#"><i class="glyphicon glyphicon-file"></i></a></td>
                              <td>Plano Martillo 2</td>
                              <td>Eintein</td>
                              <td>3 C</td>
                              <td>Ajuste</td>
                              <td>Plano necesario</td>
                              <td><a href="#"><i class="glyphicon glyphicon-edit" ></i></a>
                                <a href="#"><i class="glyphicon glyphicon-trash" style="left: 10px;"></i></a>
                                <a href="#"><i class="glyphicon glyphicon-save" style="left: 20px;"></i></a></td>
                          </tr>
                          <tr>
                              <td><a href="#"><i class="glyphicon glyphicon-file"></i></a></td>
                              <td>Apunte 1</td>
                              <td>Eintein</td>
                              <td>3 C</td>
                              <td>Ajuste</td>
                              <td>Plano necesario</td>
                              <td><a href="#"><i class="glyphicon glyphicon-edit"></i></a>
                                <a href="#"><i class="glyphicon glyphicon-trash" style="left: 10px;"></i></a>
                                <a href="#"><i class="glyphicon glyphicon-save" style="left: 20px;"></i></a></td>
                          </tr>
                        </tbody>
                    </table>
                </div>
                <input  class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal" value="Cargar Documentos" style="margin-left: 909px;"/>
            </div>

        </div>
    </div>
    <div class="col-xs-6">
        <!-- Panel "Alumnos" -->
        <div class="col-xs-12 ">
          <div id="myModal" class="modal fade">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  <h4 class="modal-title">Cargar Documentos</h4>
                </div>
                <div class="modal-body">

                  <form class="form-horizontal" enctype="multipart/form-data"  method="post" role="form" action="{% url 'app_main:doc'%}">
                    {% csrf_token %}
                    <div class="form-group col-xs-12 ">
                      <input  class="form-control" type="text" placeholder="Nombre del Documento" id="nameDocument" name="nameDocument"/>
                    </div>
                      <div class="form-group col-xs-12 ">
                      <select  class="selectpicker" data-width="100%" id="cbxCourseD" name="idCourse">
                          <option value=''>Curso</option>
                          {% for a in courses %}
                          <option value={{a.idCourse}} >{{a.courseType}}º año "{{a.courseDivision}}"</option>
                          {% endfor %}
                      </select>
                    </div>
                    <div class="form-group col-xs-12 ">
                      <select id="cbxModuleD" name="idModule" class="selectpicker" data-width="100%">
                          <option value=''>Módulo</option>
                      </select>
                      </div>
                      <div class="form-group col-xs-12">
                          <label >Descripcion</label>
                          <textarea class="form-control" rows="4" id="commentDoc" name="commentDoc"></textarea>
                      </div>
                    <input  class="filestyle" type="file" id="archivo" name="archivo"/>


                <div class="modal-footer">
                  <input  class="btn btn-default" type="submit" value="Subir archivos"/>
                </div>
                </form>

              </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
          </div><!-- /.modal -->
                  <div class="panel-body">
                    <div class="col-lg-6 col-sm-6 col-12">
                      <div class="input-group">


                      <div id="mensaje"></div>
                      </div>
          </div>
            </div>

    </div>
</div>
    </div>
    <div id="modalDeleteD" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 id='modal-title' class="modal-title">Borrar</h4>
                    </div>
                    <div class="modal-body">
                        <p id='modal-text'>Esta seguro que desea borrar este Documento?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                        <button id='deleteSelectD' type="button" class="btn btn-warning" data-dismiss="modal" onclick="docDeleter()">Si</button>
                    </div>
                </div>

            </div>
        </div>

{% endblock %}
{% block scripts %}
<script src="{% static 'js/jquery-3.1.0.js'%}"></script>
<script src="{% static 'js/bootstrap-select.js'%}"></script>
<!-- sytle input-file -->
<script src="{% static 'js/bootstrap-filestyle.min.js' %}"> </script>

<!-- Siempre antes de importar la libreria de Pern se debe agregar el siguiente elemento SCRIPT -->
<script> var url = '{% url "app_main:seg-al" %}';</script>
<script> var urlDoc = '{% url "app_main:doc" %}';</script>

<script src="{% static 'js/seg.js'%}"></script>
<script type="text/javascript">
    $('#myModal').on('shown.bs.modal', function () {
    $('#myInput').focus()
    })
</script>
<script type="text/javascript">
    $(":file").filestyle({input: false});
</script>
{% endblock %}

Pern2/Main/templates/history.html
{% extends 'base.html' %} {% load staticfiles %} {% block link4 %} class='active' {% endblock %} {% block content %}
<div class="container col-xs-12">
    <div class="col-xs-12 col-md-12">
        <!-- Panel "Alumnos" -->
        <div class="col-xs-12 col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Historial
                </div>
                <div class="panel-body">
                    <div class="form-group col-xs-12 col-md-3">
                        <select id="cbxCourseHistory" class="selectpicker" data-width="100%">
                            <option value=''>Curso</option>
                            {% for i in courses %}
                            <option value={{i.idCourse}}>{{i.courseType}}º año "{{i.courseDivision}}"</option>
                            {% endfor %}
                        </select>
                    </div>
                    <!-- <div class="form-group col-xs-12 col-md-4">
                        <select id="cbxModuleHistory" class="selectpicker" data-width="100%">
                            <option value=''>Módulo</option>
                        </select>
                    </div> -->
                    <div class="form-group col-xs-12 col-md-2">
                        <div class="input-group col-xs-12">
                            <span class="input-group-btn">
                          <button class="btn btn-default" type="button">
                              <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                            </button>
                            </span>
                            <input type="text" class="form-control" id="firstDate" name="date" placeholder="Fecha inicial">
                        </div>
                    </div>
                    <div class="form-group col-xs-12 col-md-2">
                        <div class="input-group col-xs-12">
                            <span class="input-group-btn">
                          <button class="btn btn-default" type="button">
                              <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                            </button>
                            </span>
                            <input type="text" class="form-control" id="lastDate" name="date" placeholder="Fecha inicial" data-provide="datepicker">
                        </div>
                    </div>
                    <div class="form-group col-xs-12 col-md-3">
                        <select id="cbxStudent" class="selectpicker" data-width="100%">
                            <option value=''>Alumno</option>
                        </select>
                    </div>
                    <div class="form-group col-xs-12 col-md-2">
                        <button class="btn btn-warning col-xs-12" id="btnSearchHistory" onclick="studentChanged()">Buscar</button>
                    </div>
                    <div class="table table-responsive">
                        <table class="table table-responsive" id="historyTable">
                            <thead>
                                <tr>
                                    <th class='col-xs-1'>Presente</th>
                                    <th class='col-xs-3'>Fecha</th>
                                    <th class='col-xs-6'>Tarea</th>
                                    <th class='col-xs-1'></th>
                                </tr>
                            </thead>
                            <tbody id="tbHistory">
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% block scripts %}
<script src="{% static 'js/bootstrap-select.js'%}"></script>
<!-- Siempre antes de importar la libreria de Pern se debe agregar el siguiente elemento SCRIPT -->
<script>
    var url = '{% url "app_main:seg-al" %}';
    $('#firstDate').datepicker({
    format: 'yyyy-mm-dd'
});
    $('#lastDate').datepicker({
    format: 'yyyy-mm-dd'
});
</script>
<script src="{% static 'js/seg.js'%}"></script>
{% endblock %}